import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import fg from "fast-glob";
import { RESOLVER } from "awilix";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Script lives in src/di, so src root is one level up.
const srcDir = path.resolve(__dirname, "..");
const generatedDir = path.resolve(srcDir, "di", "generated");
const manifestFile = path.resolve(generatedDir, "ioc-manifest.ts");

const ALL_SOURCE_PATTERNS = [
  "**/*.{ts,js}",
  "!**/*.d.ts",
  "!**/*.test.{ts,js}",
  "!**/*.spec.{ts,js}",
  "!di/generated/**",
  "!dist/**",
  "!node_modules/**",
];

type ExtendedResolverOptions = {
  name?: string;
  group?: string;
  lifetime?: unknown;
};

type ResolverTaggedFunction = ((...args: unknown[]) => unknown) & {
  [RESOLVER]?: ExtendedResolverOptions;
};

const isResolverTaggedFunction = (
  value: unknown,
): value is ResolverTaggedFunction => {
  return typeof value === "function" && RESOLVER in value;
};

const hasResolverToken = async (absoluteFilePath: string): Promise<boolean> => {
  const sourceText = await fs.readFile(absoluteFilePath, "utf8");
  return sourceText.includes("RESOLVER");
};

const toPosixPath = (value: string): string => value.split(path.sep).join("/");

const buildImportSpecifier = (
  manifestDir: string,
  absoluteModulePath: string,
): string => {
  const relativePath = path.relative(manifestDir, absoluteModulePath);
  const withoutExtension = relativePath.replace(/\.(ts|js)$/, "");
  const normalized = toPosixPath(withoutExtension);
  return normalized.startsWith(".") ? normalized : `./${normalized}`;
};

const buildModuleKey = (absoluteModulePath: string): string => {
  return toPosixPath(path.relative(srcDir, absoluteModulePath));
};

const main = async (): Promise<void> => {
  const candidateRelativePaths = await fg(ALL_SOURCE_PATTERNS, {
    cwd: srcDir,
    absolute: false,
  });

  const candidateAbsolutePaths = candidateRelativePaths.map((relativePath) =>
    path.resolve(srcDir, relativePath),
  );

  const resolverTokenPaths: string[] = [];
  for (const absolutePath of candidateAbsolutePaths) {
    if (await hasResolverToken(absolutePath)) {
      resolverTokenPaths.push(absolutePath);
    }
  }

  const manifestEntries: Array<{
    absolutePath: string;
    moduleKey: string;
    exportNames: string[];
    importName: string;
    importSpecifier: string;
  }> = [];

  let importIndex = 0;

  for (const absolutePath of resolverTokenPaths) {
    const moduleUrl = pathToFileURL(absolutePath).href;
    const moduleExports = (await import(moduleUrl)) as Record<string, unknown>;

    const resolverExportNames = Object.entries(moduleExports)
      .filter(([, value]) => isResolverTaggedFunction(value))
      .map(([exportName]) => exportName)
      .sort();

    if (resolverExportNames.length === 0) {
      continue;
    }

    importIndex += 1;

    manifestEntries.push({
      absolutePath,
      moduleKey: buildModuleKey(absolutePath),
      exportNames: resolverExportNames,
      importName: `module${importIndex}`,
      importSpecifier: buildImportSpecifier(generatedDir, absolutePath),
    });
  }

  manifestEntries.sort((a, b) => a.moduleKey.localeCompare(b.moduleKey));

  const fileContents = `/* eslint-disable */
// AUTO-GENERATED FILE. DO NOT EDIT.
// Generated by scripts/generate-ioc-manifest.ts

import type { IocManifest } from "../ioc-manifest-types";
${manifestEntries
  .map(
    (entry) =>
      `import * as ${entry.importName} from "${entry.importSpecifier}";`,
  )
  .join("\n")}

export const iocManifest: IocManifest = [
${manifestEntries
  .map(
    (entry) => `  {
    modulePath: "${entry.moduleKey}",
    exports: ${entry.importName},
  },`,
  )
  .join("\n")}
];
`;

  await fs.mkdir(generatedDir, { recursive: true });
  await fs.writeFile(manifestFile, fileContents, "utf8");

  process.stdout.write(
    `[generate-ioc-manifest] Wrote ${manifestEntries.length} module entries to ${manifestFile}\n`,
  );
};

main().catch((error) => {
  process.stderr.write(
    `[generate-ioc-manifest] Failed: ${
      error instanceof Error ? (error.stack ?? error.message) : String(error)
    }\n`,
  );
  process.exit(1);
});
